language: rust
sudo: false

matrix:
  include:
    - rust: 1.15.0
    - rust: stable
    - rust: stable
      os: osx
    - rust: beta
    - rust: nightly
      script:
        - cargo bench
        - cargo test
        - cargo test --features nightly
        - cargo test --manifest-path rand-derive/Cargo.toml
        - cargo doc --no-deps --features nightly
script:
  - cargo test
  - cargo test --manifest-path rand-derive/Cargo.toml

deploy:
  - provider: script
    script: .doc-upload.sh
    on:
      branch: master
      condition: $TRAVIS_OS_NAME = linux
env:
  global:
    secure: "BdDntVHSompN+Qxz5Rz45VI4ZqhD72r6aPl166FADlnkIwS6N6FLWdqs51O7G5CpoMXEDvyYrjmRMZe/GYLIG9cmqmn/wUrWPO+PauGiIuG/D2dmfuUNvSTRcIe7UQLXrfP3yyfZPgqsH6pSnNEVopquQKy3KjzqepgriOJtbyY="

notifications:
  email:
    on_success: never
