language: rust
sudo: false

matrix:
  include:
    - rust: 1.22.0
      script:
        - cargo test
        - cargo build --no-default-features # we cannot exclude doc tests
    - rust: stable
    - rust: stable
      os: osx
    - rust: beta
    - rust: nightly

    - rust: nightly
      before_script:
        - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH
      script:
        - cargo doc --no-deps --all-features
        - cargo test --benches
        - cargo test --features nightly
        - cargo test --tests --no-default-features --features=alloc
      after_success:
        - travis-cargo --only nightly doc-upload
    
    # Trust cross-built/emulated targets. We must repeat all non-default values.
    - rust: stable
      sudo: required
      dist: trusty
      services: docker
      install:
        - sh utils/ci/install.sh
        - source ~/.cargo/env || true
      script:
        - bash utils/ci/script.sh
      env: TARGET=i686-unknown-linux-gnu NIGHTLY=1
    - rust: stable
      sudo: required
      dist: trusty
      services: docker
      install:
        - sh utils/ci/install.sh
        - source ~/.cargo/env || true
      script:
        - bash utils/ci/script.sh
      env: TARGET=x86_64-unknown-freebsd DISABLE_TESTS=1
    - rust: stable
      sudo: required
      dist: trusty
      services: docker
      install:
        - sh utils/ci/install.sh
        - source ~/.cargo/env || true
      script:
        - bash utils/ci/script.sh
      env: TARGET=mips64-unknown-linux-gnuabi64
    - rust: stable
      sudo: required
      dist: trusty
      services: docker
      install:
        - sh utils/ci/install.sh
        - source ~/.cargo/env || true
      script:
        - bash utils/ci/script.sh
      env: TARGET=armv7-linux-androideabi DISABLE_TESTS=1
    - rust: stable
      sudo: required
      dist: trusty
      services: docker
      install:
        - sh utils/ci/install.sh
        - source ~/.cargo/env || true
      script:
        - bash utils/ci/script.sh
      # Bare metal target; no std
      env: TARGET=thumbv6m-none-eabi DISABLE_STD=1

before_install:
  - set -e
  - rustup self update

script:
  - cargo test
  - cargo test --tests --no-default-features
  - cargo test --features serde-1,log
  - cargo test --tests --no-default-features --features=serde-1

after_script: set +e

cache: cargo
before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

env:
  global:
    secure: "BdDntVHSompN+Qxz5Rz45VI4ZqhD72r6aPl166FADlnkIwS6N6FLWdqs51O7G5CpoMXEDvyYrjmRMZe/GYLIG9cmqmn/wUrWPO+PauGiIuG/D2dmfuUNvSTRcIe7UQLXrfP3yyfZPgqsH6pSnNEVopquQKy3KjzqepgriOJtbyY="

notifications:
  email:
    on_success: never
