[package]

name = "rand"
version = "0.1.2"
authors = ["The Rust Project Developers"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/rust-lang/rand"
documentation = "http://doc.rust-lang.org/rand"
homepage = "https://github.com/rust-lang/rand"
description = """
Random number generators and other randomness functionality.
"""

[dependencies]
log = "0.2.1"
libc = "0.1.1"
